# PostgreSQL for Account Service (Bank Customers)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-account-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-account-config
  namespace: infra
data:
  POSTGRES_DB: accountdb
  POSTGRES_USER: accountservice
  POSTGRES_PASSWORD: accountpass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-account
  namespace: infra
  labels:
    app: postgres-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-account
  template:
    metadata:
      labels:
        app: postgres-account
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-account-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-account-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-account
  namespace: infra
spec:
  selector:
    app: postgres-account
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
