# PostgreSQL for Notification Service
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-notification-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-notification-config
  namespace: infra
data:
  POSTGRES_DB: notificationdb
  POSTGRES_USER: notification
  POSTGRES_PASSWORD: notification123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-notification
  namespace: infra
  labels:
    app: postgres-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-notification
  template:
    metadata:
      labels:
        app: postgres-notification
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-notification-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-notification-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: infra
spec:
  selector:
    app: postgres-notification
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
